name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Debug Vercel Env Variables
        run: |
          echo "VERCEL_ORG_ID: ${{ env.VERCEL_ORG_ID }}"
          echo "VERCEL_PROJECT_ID: ${{ env.VERCEL_PROJECT_ID }}"
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ env.VERCEL_ORG_ID }}
          vercel-project-id: ${{ env.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./ 